#!/bin/bash

GOOS=darwin GOARCH=amd64 go build -o spago-build/darwin_amd64/spago
GOOS=darwin GOARCH=386 go build -o spago-build/darwin_386/spago
GOOS=linux GOARCH=amd64 go build -o spago-build/linux_amd64/spago
GOOS=linux GOARCH=386 go build -o spago-build/linux_386/spago
GOOS=windows GOARCH=amd64 go build -o spago-build/windows_amd64/spago.exe
GOOS=windows GOARCH=386 go build -o spago-build/windows_386/spago.exe
